"""init

Revision ID: d9708a474c36
Revises: 
Create Date: 2025-11-13 20:55:35.195261

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9708a474c36'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_links',
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_links_id'), 'short_links', ['id'], unique=False)
    op.create_index(op.f('ix_short_links_short_code'), 'short_links', ['short_code'], unique=True)
    op.create_table('link_visits',
    sa.Column('short_link_id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['short_link_id'], ['short_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_visits_id'), 'link_visits', ['id'], unique=False)
    op.create_index(op.f('ix_link_visits_short_link_id'), 'link_visits', ['short_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_visits_short_link_id'), table_name='link_visits')
    op.drop_index(op.f('ix_link_visits_id'), table_name='link_visits')
    op.drop_table('link_visits')
    op.drop_index(op.f('ix_short_links_short_code'), table_name='short_links')
    op.drop_index(op.f('ix_short_links_id'), table_name='short_links')
    op.drop_table('short_links')
    # ### end Alembic commands ###
